// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKHvcJpQ8wyrOYqkRKDfUnLkNkv6qX0LA',
    appId: '1:220558927008:web:7c9087c5f7dca2581d95c5',
    messagingSenderId: '220558927008',
    projectId: 'sanchalan-aeef9',
    authDomain: 'sanchalan-aeef9.firebaseapp.com',
    storageBucket: 'sanchalan-aeef9.appspot.com',
    measurementId: 'G-Y1BL380V2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdTE527oIcl9rHDLZYqiUP5LXaomYa_ds',
    appId: '1:220558927008:android:12008435731c247a1d95c5',
    messagingSenderId: '220558927008',
    projectId: 'sanchalan-aeef9',
    storageBucket: 'sanchalan-aeef9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcMRYkp3njx8HzRS-jQSm_RSgJvTdXPos',
    appId: '1:220558927008:ios:0033abdc75a694d21d95c5',
    messagingSenderId: '220558927008',
    projectId: 'sanchalan-aeef9',
    storageBucket: 'sanchalan-aeef9.appspot.com',
    iosBundleId: 'com.example.sanchalan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcMRYkp3njx8HzRS-jQSm_RSgJvTdXPos',
    appId: '1:220558927008:ios:963b0177060c64591d95c5',
    messagingSenderId: '220558927008',
    projectId: 'sanchalan-aeef9',
    storageBucket: 'sanchalan-aeef9.appspot.com',
    iosBundleId: 'com.example.sanchalan.RunnerTests',
  );
}
